services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    expose:
      - "${MARIADB_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - wordpress_network
    restart: always
    init: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    expose:
      - "${PHP_FPM_PORT}"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - WP_DB_HOST=${WP_DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    networks:
      - wordpress_network
    restart: always
    init: true

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ${CERTS_PATH}:/etc/nginx/ssl:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: always
    init: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_VOLUME}
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME}
      o: bind

networks:
  wordpress_network:
    driver: bridge

secrets:
  db_password:
    file: ${DB_PASSWORD_FILE}
  db_root_password:
    file: ${DB_ROOT_PASSWORD_FILE}
  wp_admin_password:
    file: ${WP_ADMIN_PASSWORD_FILE}
  wp_user_password:
    file: ${WP_USER_PASSWORD_FILE}